name: Azure Deployment

on:
    workflow_dispatch:

env:
    RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: |
                        ${{ secrets.CRED }}

            - name: Deploy ARM template
              uses: azure/arm-deploy@v1
              with:
                  resourceGroupName: ${{ env.RESOURCE_GROUP }}
                  template: ./InfrastructureAsCode/main.bicep
                  parameters: environment=dev