name: My first workflow

on: [push, pull_request]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo a message 1
        run: echo "Hello, Step1!"
      - name: Echo a message 2
        run: echo "Hello, Step2!"    
  new_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use cowsay action
        uses: aslafy-z/cowsay-action@master
        with:
          text: "Hello, from cowsay!"