name: First Workflow

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: Step 1
            run: echo "step1"
          - name: Step 2
            run: echo "step2"
            
    cow:
      name: Cowsays
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - name: Ship it
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: 'ship ship ship!'
            color: 'blue'

    issue:
      name: Issue Trigger
      runs-on: ubuntu-latest
      steps:
        - name: Issue Created
          uses: actions/github-script@v4
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              console.log('Issue created:', context.payload.issue?.number)
